#########################
## Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# File Options
files:
  include: 'scss/**/*.s+(a|c)ss'
  ignore:
    - 'src/scss/vendors/**/*.*'
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  mixins-before-declarations:
    - 2
    - exclude: ['breakpoint', 'mq', 'media']
  hex-notation:
    - 1
    - style: lowercase
  indentation:
    - 1
    - size: tab
  no-empty-rulesets: 2
  no-misspelled-properties: 2
  no-trailing-zero: 2
  no-transition-all: 1
  no-url-domains: 1
  shorthand-values: 1
  nesting-depth:
    - 2
    - max-depth: 4









